stages:
 - build

before_script:
  - cd $CI_PROJECT_DIR
  - rm -rf bin obj
  - rm -rf Installer/bin Installer/obj
  - curl https://dist.nuget.org/win-x86-commandline/latest/nuget.exe --output nuget.exe

build:win:rel:
  stage: build
  tags: ['win','bash']

  script:
    - ./nuget.exe restore VLAlarmViewer.sln
    - "\"C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe\" \"VLAlarmViewer.sln\" //t:Build //p:Configuration=Release //p:TargetFramework=v4.5 //m"
    - mkdir VLAlarmViewer
    - cp Installer/bin/x64/Release/* VLAlarmViewer/

  artifacts:
    name: "vl_milestone_alarm_viewer_$(if [[ ! -z ${CI_BUILD_TAG} ]]; then echo ${CI_BUILD_TAG}; else echo ${CI_BUILD_REF}; fi)"
    expire_in: '10d'
    paths:
      - $CI_PROJECT_DIR/VLAlarmViewer
